[project]
name = "ctfddash"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.2",
    "flask-socketio>=5.6.0",
    "requests>=2.32.5",
    "toml>=0.10.2",
]
